#!/usr/bin/env ruby
require 'date'

args = ARGV
name = ARGV[0]
birthday = ARGV[1]
non_letters = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "@", "#", "$", "%", "^", "&", "*", "/"]

def exit_with_error
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers.rb [Name] [MM/DD Birthday]`
EOS
  exit
end
# '

if args.empty?
  exit_with_error
end

cheerable_name = name.upcase.gsub(/[^A-Z]/, "")

if cheerable_name.empty?
  exit_with_error
end


if non_letters.any? { |i| name.include? i } == true
  exit_with_error
end


cheerable_name.each_char do |letter|
  an_letters = "AEFHILMNORSX"
  article = "a"
  article = an_letters.include?(letter) ? "an" : "a"
  puts "Give me #{article}... #{letter}"
end
puts "#{name}'s just GRAND!"
puts "I would wish you a Happy Birthday, if I knew when that was!"

date = Date.parse(birthday)
if date.include?(date.year)
  cheerable_name.each_char do |letter|
    an_letters = "AEFHILMNORSX"
    article = "a"
    article = an_letters.include?(letter) ? "an" : "a"
    puts "Give me #{article}... #{letter}"
  end
  puts "#{name}'s just GRAND!"
  puts "I would wish you a Happy Birthday, if I knew when that was!"
end
